import type { NextPage } from "next";
import Head from "next/head";
import Table from "../components/Table";
import { FlexCenter, Title } from "../styles/base.style";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>CRUD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main>
          <FlexCenter>
            <Title>C R U D ___ Table</Title>
          </FlexCenter>
          <Table />
        </main>

    </>
  );
};

export default Home;
